esphome:
  name: bthome-receiver

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
- source:
    type: local
    path: components
  components: [ bthome_receiver ]

api:
logger:

# Enable BLE scanning
esp32_ble_tracker:

# BTHome Receiver Hub
bthome_receiver:
  devices:
  - mac_address: "AA:BB:CC:DD:EE:FF"
    name: "Living Room Sensor"

# Receive temperature and humidity from BTHome device
sensor:
- platform: bthome_receiver
  mac_address: "AA:BB:CC:DD:EE:FF"
  temperature:
    name: "Living Room Temperature"
  humidity:
    name: "Living Room Humidity"
  battery:
    name: "Living Room Battery"

# Receive motion detection from BTHome device
binary_sensor:
- platform: bthome_receiver
  mac_address: "AA:BB:CC:DD:EE:FF"
  motion:
    name: "Living Room Motion"
  door:
    name: "Living Room Door"
